// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHhWFOibvjrkCuLwGdsuZHTAtDd9VpmU',
    appId: '1:287848300229:web:3b5b2754d16f0009b73aac',
    messagingSenderId: '287848300229',
    projectId: 'appocgf01',
    authDomain: 'appocgf01.firebaseapp.com',
    storageBucket: 'appocgf01.appspot.com',
    measurementId: 'G-TEPM65VT0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhh6GWMfRumH53pnbw7TF2N7os2YAhZQ',
    appId: '1:287848300229:android:120b475268ae6285b73aac',
    messagingSenderId: '287848300229',
    projectId: 'appocgf01',
    storageBucket: 'appocgf01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXjKnZTTIHlLvlPtwajprYDVKXSKGzL8',
    appId: '1:287848300229:ios:6e9b61ecb36654c8b73aac',
    messagingSenderId: '287848300229',
    projectId: 'appocgf01',
    storageBucket: 'appocgf01.appspot.com',
    iosBundleId: 'com.example.appOcgf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXjKnZTTIHlLvlPtwajprYDVKXSKGzL8',
    appId: '1:287848300229:ios:6e9b61ecb36654c8b73aac',
    messagingSenderId: '287848300229',
    projectId: 'appocgf01',
    storageBucket: 'appocgf01.appspot.com',
    iosBundleId: 'com.example.appOcgf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHhWFOibvjrkCuLwGdsuZHTAtDd9VpmU',
    appId: '1:287848300229:web:9e03eca6e3c82a8eb73aac',
    messagingSenderId: '287848300229',
    projectId: 'appocgf01',
    authDomain: 'appocgf01.firebaseapp.com',
    storageBucket: 'appocgf01.appspot.com',
    measurementId: 'G-S8FK448QGW',
  );

}